version: '2'
volumes:
    monitor_elasticsearch:
        external: true
    monitor_logstash:
        external: true
    monitor_logstash_pipeline:
        external: true
    monitor_kibana:
        external: true
services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - /opt/docker/volume/monitor/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - monitor_logstash:/usr/share/logstash/config
      - monitor_logstash_pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - monitor_kibana:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
